#!/bin/bash
#####################
# Author: Deepthi
# Date: 01/17/25
# Version: v1
# This script will report the aws resource usage
#
# ##################
# AWS S3
# AWS EC2
# AWS lambda
# AWS IAM users

set -x
#list s3 buckets
echo "Print list of s3 buckets"
aws s3 ls

#list ec2 instances
echo "Print list of EC2 instances"
aws ec2 describe-instances

#list lambda
echo "Print list of lambda functions"
aws lambda list-functions

#list iam users
echo "Print list of iam users"
aws iam list-users



#To get only InstanceId from then ec2 instances we use:
aws ec2 describe-instances | jq '.Reseravtions[].Instances[].InstanceId'     #Here jq is used because the output is in JSON format.